version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgresorganization
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=organization
      - POSTGRES_HOST=postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data:Z

  pgadmin:
    container_name: pgadminorganization
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5050:80"

volumes:
  db_data: